CREATE DATABASE sms_viewer;

USE sms_viewer;

CREATE TABLE Users (
  id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(50) NOT NULL
);

CREATE TABLE SMS (
  id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT(11) NOT NULL,
  channel_id INT(11) NOT NULL,
  description TEXT NOT NULL,
  data TEXT NOT NULL,
  save BOOLEAN NOT NULL DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES Users(id)
);

CREATE TABLE Channel (
  id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  description TEXT NOT NULL,
  data TEXT NOT NULL,
  like BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE Field (
  id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  description TEXT NOT NULL,
  data TEXT NOT NULL
);

CREATE TABLE Field_Channel (
  id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  field_id INT(11) NOT NULL,
  channel_id INT(11) NOT NULL,
  FOREIGN KEY (field_id) REFERENCES Field(id),
  FOREIGN KEY (channel_id) REFERENCES Channel(id)
);
